using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GrcMvc.Models.Entities;
using GrcMvc.Services.Interfaces;
using GrcMvc.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GrcMvc.Controllers.Api
{
    /// <summary>
    /// Simplified Platform Admin API for tenant management
    /// </summary>
    [ApiController]
    [Route("api/platform/admin")]
    [Authorize(Roles = "PlatformAdmin,SuperAdmin")]
    public class SimplePlatformAdminController : ControllerBase
    {
        private readonly ITenantService _tenantService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly GrcDbContext _dbContext;
        private readonly ILogger<SimplePlatformAdminController> _logger;

        public SimplePlatformAdminController(
            ITenantService tenantService,
            UserManager<ApplicationUser> userManager,
            GrcDbContext dbContext,
            ILogger<SimplePlatformAdminController> logger)
        {
            _tenantService = tenantService;
            _userManager = userManager;
            _dbContext = dbContext;
            _logger = logger;
        }

        /// <summary>
        /// Create a new tenant
        /// </summary>
        [HttpPost("create-tenant")]
        public async Task<IActionResult> CreateTenant([FromBody] SimpleTenantRequest request)
        {
            try
            {
                // Step 1: Create Tenant
                var tenant = await _tenantService.CreateTenantAsync(
                    request.OrganizationName,
                    request.AdminEmail,
                    request.TenantSlug);
                
                // Step 2: Activate tenant immediately (platform admin privilege)
                tenant.Status = "Active";
                tenant.IsActive = true;
                tenant.ActivatedAt = DateTime.UtcNow;
                tenant.ActivatedBy = User.Identity?.Name ?? "platform-admin";
                _dbContext.Update(tenant);
                await _dbContext.SaveChangesAsync();
                
                // Step 3: Create admin user
                var adminUser = new ApplicationUser
                {
                    // Id is auto-generated by ABP Identity - don't set manually
                    FirstName = request.AdminFirstName,
                    LastName = request.AdminLastName,
                    CreatedAt = DateTime.UtcNow,
                    MustChangePassword = true
                };
                
                var password = GeneratePassword();
                var result = await _userManager.CreateAsync(adminUser, password);
                
                if (!result.Succeeded)
                {
                    return BadRequest(new { errors = result.Errors });
                }
                
                // Set UserName and Email using UserManager methods
                await _userManager.SetUserNameAsync(adminUser, request.AdminEmail);
                await _userManager.SetEmailAsync(adminUser, request.AdminEmail);
                
                // Confirm email for admin user
                var token = await _userManager.GenerateEmailConfirmationTokenAsync(adminUser);
                await _userManager.ConfirmEmailAsync(adminUser, token);
                
                // Assign Admin role
                await _userManager.AddToRoleAsync(adminUser, "Admin");
                
                // Update tenant with admin ID (convert Guid to string)
                tenant.FirstAdminUserId = adminUser.Id.ToString();
                _dbContext.Update(tenant);
                await _dbContext.SaveChangesAsync();
                
                _logger.LogInformation("Tenant {TenantSlug} created successfully by platform admin", tenant.TenantSlug);
                
                return Ok(new
                {
                    success = true,
                    tenantId = tenant.Id,
                    tenantSlug = tenant.TenantSlug,
                    adminEmail = adminUser.Email,
                    temporaryPassword = password,
                    message = "Tenant created successfully"
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating tenant");
                return StatusCode(500, new { error = ex.Message });
            }
        }

        /// <summary>
        /// List all tenants
        /// </summary>
        [HttpGet("tenants")]
        public async Task<IActionResult> ListTenants()
        {
            var tenants = await _dbContext.Tenants
                .Where(t => !t.IsDeleted)
                .OrderByDescending(t => t.CreatedDate)
                .Select(t => new
                {
                    t.Id,
                    t.TenantSlug,
                    t.TenantCode,
                    t.OrganizationName,
                    t.Status,
                    t.IsActive,
                    t.AdminEmail,
                    t.CreatedDate,
                    t.SubscriptionTier
                })
                .ToListAsync();
                
            return Ok(tenants);
        }

        /// <summary>
        /// Activate/Deactivate tenant
        /// </summary>
        [HttpPost("tenant/{tenantId}/status")]
        public async Task<IActionResult> SetTenantStatus(Guid tenantId, [FromBody] TenantStatusRequest request)
        {
            var tenant = await _dbContext.Tenants.FindAsync(tenantId);
            if (tenant == null)
                return NotFound("Tenant not found");
                
            tenant.IsActive = request.IsActive;
            tenant.Status = request.IsActive ? "Active" : "Suspended";
            
            await _dbContext.SaveChangesAsync();
            
            return Ok(new { message = "Status updated", status = tenant.Status });
        }

        private string GeneratePassword()
        {
            return $"Admin@{Guid.NewGuid().ToString("N").Substring(0, 8)}!2026";
        }
    }

    public class SimpleTenantRequest
    {
        public string OrganizationName { get; set; }
        public string TenantSlug { get; set; }
        public string AdminEmail { get; set; }
        public string AdminFirstName { get; set; }
        public string AdminLastName { get; set; }
    }

    public class TenantStatusRequest
    {
        public bool IsActive { get; set; }
    }
}
